"""RES-131: canonical scientific document model.

Creates the canonical tables — ``source_artifact``, ``document``,
``document_identifier``, ``document_version``, ``section``, ``passage``,
``citation``, ``document_table`` and ``figure`` — with the full constraint
set that makes the domain invariants enforceable by the database itself:

* deterministic canonical keys (``artifact_key``, ``canonical_key``,
  ``version_key``, ``section_key``, ``passage_key``, ``citation_key``,
  ``document_table_key``, ``figure_key``) carry UNIQUE constraints, so a
  repeated deterministic identity collides instead of duplicating;
* SHA-256 columns carry CHECK constraints requiring lowercase 64-character
  hexadecimal, mirroring the domain-layer validation;
* composite foreign keys force a section's parent, a passage's owning
  section and a table/figure's owning section to belong to the same
  ``document_version``;
* ``document.identifier`` aliases are globally unique per
  ``(namespace, normalized_value)`` and immutable, so identifier enrichment
  never re-identifies a document;
* every timestamp is ``TIMESTAMPTZ`` and every table has a
  ``row_created_at`` defaulted to the transaction timestamp.

Like revision 0001, this migration is hand-written and reviewed rather than
autogenerated; see ``alembic/env.py`` for why no ``MetaData`` is registered.

Revision ID: 0002_canonical_document_model
Revises: 0001_foundation_baseline
Create Date: 2026-09-27T23:30:00.000000Z
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_canonical_document_model"
down_revision: str | None = "0001_foundation_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_HEX64 = "~ '^[0-9a-f]{64}$'"
_DOI_FORMAT = "~ '^10\\.[0-9]{4,9}/\\S+$'"
_PMAD_FORMAT = "~ '^[0-9]{1,10}$'"
_PMCID_FORMAT = "~ '^PMC[0-9]{1,12}$'"
_LANGUAGE_FORMAT = "~ '^[a-z]{2,3}$'"
_PATH_FORMAT = "~ '^[0-9]+(\\.[0-9]+)*$'"

_CANONICAL_TABLES = (
    "source_artifact",
    "document",
    "document_identifier",
    "document_version",
    "section",
    "passage",
    "citation",
    "document_table",
    "figure",
)
"""Every canonical table is append-only; immutable operational state, if it
is ever needed, belongs on separate tables rather than on these records."""

_IMMUTABLE_FUNCTION = """
CREATE OR REPLACE FUNCTION dynamisrag_enforce_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'dynamisrag: % on canonical table % is prohibited; canonical records are append-only',
        TG_OP, TG_TABLE_NAME
    USING ERRCODE = 'P0001';
END;
$$;
"""
"""One small generic trigger function guards every canonical table.

Only UPDATE and DELETE are blocked: appending is the supported write, and
TRUNCATE is left to operations tooling rather than to row-level enforcement.
"""

_ROW_CREATED_AT = sa.Column(
    "row_created_at",
    sa.DateTime(timezone=True),
    nullable=False,
    server_default=sa.func.now(),
)


def upgrade() -> None:
    """Apply this revision: create the canonical scientific document schema."""

    op.create_table(
        "source_artifact",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("source_system", sa.Text, nullable=False),
        sa.Column("source_external_id", sa.Text, nullable=False),
        sa.Column("source_uri", sa.Text, nullable=False),
        sa.Column("media_type", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.Text, nullable=False),
        sa.Column("byte_size", sa.BigInteger, nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_uri", sa.Text, nullable=False),
        sa.Column("license_name", sa.Text, nullable=True),
        sa.Column("license_uri", sa.Text, nullable=True),
        sa.Column("artifact_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_source_artifact"),
        sa.UniqueConstraint("artifact_key", name="uq_source_artifact_artifact_key"),
        sa.CheckConstraint("byte_size >= 0", name="ck_source_artifact_byte_size_nonnegative"),
        sa.CheckConstraint(
            f"content_sha256 {_HEX64}",
            name="ck_source_artifact_content_sha256_hex",
        ),
    )
    op.create_index(
        "ix_source_artifact_source_lookup",
        "source_artifact",
        ["source_system", "source_external_id"],
    )

    op.create_table(
        "document",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("canonical_key", sa.Text, nullable=False),
        sa.Column("document_type", sa.Text, nullable=False),
        sa.Column("title", sa.Text, nullable=True),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_document"),
        sa.UniqueConstraint("canonical_key", name="uq_document_canonical_key"),
    )

    op.create_table(
        "document_identifier",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_id", sa.Uuid, nullable=False),
        sa.Column("namespace", sa.Text, nullable=False),
        sa.Column("normalized_value", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_document_identifier"),
        sa.UniqueConstraint(
            "namespace", "normalized_value", name="uq_document_identifier_namespace_value"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name="fk_document_identifier_document"
        ),
        sa.CheckConstraint(
            "namespace IN ('doi', 'pmid', 'pmcid')", name="ck_document_identifier_namespace"
        ),
        sa.CheckConstraint(
            "(namespace = 'doi' AND normalized_value " + _DOI_FORMAT + ")"
            " OR (namespace = 'pmid' AND normalized_value " + _PMAD_FORMAT + ")"
            " OR (namespace = 'pmcid' AND normalized_value " + _PMCID_FORMAT + ")",
            name="ck_document_identifier_value_format",
        ),
    )
    op.create_index("ix_document_identifier_document_id", "document_identifier", ["document_id"])

    op.create_table(
        "document_version",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_id", sa.Uuid, nullable=False),
        sa.Column("source_artifact_id", sa.Uuid, nullable=False),
        sa.Column("parser_revision", sa.Text, nullable=False),
        sa.Column("normalizer_revision", sa.Text, nullable=False),
        sa.Column("content_fingerprint", sa.Text, nullable=False),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("language", sa.Text, nullable=False),
        sa.Column(
            "versioned_metadata",
            sa.dialects.postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_document_version"),
        sa.UniqueConstraint("version_key", name="uq_document_version_version_key"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name="fk_document_version_document"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name="fk_document_version_source_artifact",
        ),
        sa.CheckConstraint(
            f"content_fingerprint {_HEX64}",
            name="ck_document_version_content_fingerprint_hex",
        ),
        sa.CheckConstraint(
            f"language {_LANGUAGE_FORMAT}", name="ck_document_version_language_code"
        ),
    )
    op.create_index("ix_document_version_document_id", "document_version", ["document_id"])
    op.create_index(
        "ix_document_version_source_artifact_id",
        "document_version",
        ["source_artifact_id"],
    )

    op.create_table(
        "section",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_version_id", sa.Uuid, nullable=False),
        sa.Column("parent_section_id", sa.Uuid, nullable=True),
        sa.Column("parent_document_version_id", sa.Uuid, nullable=True),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("depth", sa.Integer, nullable=False),
        sa.Column("title", sa.Text, nullable=True),
        sa.Column("semantic_type", sa.Text, nullable=True),
        sa.Column("source_anchor", sa.Text, nullable=True),
        sa.Column("structural_path", sa.Text, nullable=False),
        sa.Column("content_fingerprint", sa.Text, nullable=True),
        sa.Column("section_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_section"),
        sa.UniqueConstraint("id", "document_version_id", name="uq_section_id_document_version_id"),
        sa.UniqueConstraint(
            "document_version_id", "section_key", name="uq_section_document_version_section_key"
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name="fk_section_document_version",
        ),
        sa.ForeignKeyConstraint(
            ["parent_section_id", "parent_document_version_id"],
            ["section.id", "section.document_version_id"],
            name="fk_section_parent",
        ),
        sa.CheckConstraint(
            "(parent_section_id IS NULL) = (parent_document_version_id IS NULL)",
            name="ck_section_parent_pair",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_section_ordinal_nonnegative"),
        sa.CheckConstraint("depth >= 0", name="ck_section_depth_nonnegative"),
        sa.CheckConstraint(
            f"structural_path {_PATH_FORMAT}", name="ck_section_structural_path_canonical"
        ),
        sa.CheckConstraint(
            f"content_fingerprint IS NULL OR content_fingerprint {_HEX64}",
            name="ck_section_content_fingerprint_hex",
        ),
    )
    op.create_index("ix_section_document_version_id", "section", ["document_version_id"])

    op.create_table(
        "passage",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_version_id", sa.Uuid, nullable=False),
        sa.Column("section_id", sa.Uuid, nullable=True),
        sa.Column("section_document_version_id", sa.Uuid, nullable=True),
        sa.Column("chunker_revision", sa.Text, nullable=False),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.Text, nullable=False),
        sa.Column("source_anchor", sa.Text, nullable=True),
        sa.Column("token_count", sa.Integer, nullable=True),
        sa.Column("passage_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_passage"),
        sa.UniqueConstraint(
            "document_version_id",
            "chunker_revision",
            "ordinal",
            name="uq_passage_version_chunker_ordinal",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name="fk_passage_document_version",
        ),
        sa.ForeignKeyConstraint(
            ["section_id", "section_document_version_id"],
            ["section.id", "section.document_version_id"],
            name="fk_passage_section",
        ),
        sa.CheckConstraint(
            "(section_id IS NULL) = (section_document_version_id IS NULL)",
            name="ck_passage_section_pair",
        ),
        sa.CheckConstraint(f"content_sha256 {_HEX64}", name="ck_passage_content_sha256_hex"),
        sa.CheckConstraint("ordinal >= 0", name="ck_passage_ordinal_nonnegative"),
        sa.CheckConstraint(
            "token_count IS NULL OR token_count >= 0",
            name="ck_passage_token_count_nonnegative",
        ),
    )
    op.create_index("ix_passage_document_version_id", "passage", ["document_version_id"])
    op.create_index("ix_passage_section_id", "passage", ["section_id"])

    op.create_table(
        "citation",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_version_id", sa.Uuid, nullable=False),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("source_reference_id", sa.Text, nullable=True),
        sa.Column("doi", sa.Text, nullable=True),
        sa.Column("pmid", sa.Text, nullable=True),
        sa.Column("pmcid", sa.Text, nullable=True),
        sa.Column("title", sa.Text, nullable=True),
        sa.Column("year", sa.Integer, nullable=True),
        sa.Column("raw_reference_text", sa.Text, nullable=True),
        sa.Column("resolved_document_id", sa.Uuid, nullable=True),
        sa.Column("citation_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_citation"),
        sa.UniqueConstraint(
            "document_version_id", "ordinal", name="uq_citation_document_version_ordinal"
        ),
        sa.UniqueConstraint(
            "document_version_id",
            "citation_key",
            name="uq_citation_document_version_key",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name="fk_citation_document_version",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_document_id"], ["document.id"], name="fk_citation_resolved_document"
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_citation_ordinal_nonnegative"),
        sa.CheckConstraint(
            "year IS NULL OR (year >= 1000 AND year <= 2200)",
            name="ck_citation_year_plausible",
        ),
        sa.CheckConstraint("doi IS NULL OR doi " + _DOI_FORMAT, name="ck_citation_doi_format"),
        sa.CheckConstraint("pmid IS NULL OR pmid " + _PMAD_FORMAT, name="ck_citation_pmid_format"),
        sa.CheckConstraint(
            "pmcid IS NULL OR pmcid " + _PMCID_FORMAT, name="ck_citation_pmcid_format"
        ),
    )
    op.create_index("ix_citation_document_version_id", "citation", ["document_version_id"])
    op.create_index("ix_citation_resolved_document_id", "citation", ["resolved_document_id"])

    op.create_table(
        "document_table",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_version_id", sa.Uuid, nullable=False),
        sa.Column("section_id", sa.Uuid, nullable=True),
        sa.Column("section_document_version_id", sa.Uuid, nullable=True),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("label", sa.Text, nullable=True),
        sa.Column("caption", sa.Text, nullable=True),
        sa.Column("source_anchor", sa.Text, nullable=True),
        sa.Column(
            "structured_representation",
            sa.dialects.postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("content_fingerprint", sa.Text, nullable=True),
        sa.Column("document_table_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_document_table"),
        sa.UniqueConstraint(
            "document_version_id",
            "document_table_key",
            name="uq_document_table_document_version_key",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name="fk_document_table_document_version",
        ),
        sa.ForeignKeyConstraint(
            ["section_id", "section_document_version_id"],
            ["section.id", "section.document_version_id"],
            name="fk_document_table_section",
        ),
        sa.CheckConstraint(
            "(section_id IS NULL) = (section_document_version_id IS NULL)",
            name="ck_document_table_section_pair",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_document_table_ordinal_nonnegative"),
        sa.CheckConstraint(
            f"content_fingerprint IS NULL OR content_fingerprint {_HEX64}",
            name="ck_document_table_content_fingerprint_hex",
        ),
    )
    op.create_index(
        "ix_document_table_document_version_id", "document_table", ["document_version_id"]
    )
    op.create_index("ix_document_table_section_id", "document_table", ["section_id"])

    op.create_table(
        "figure",
        sa.Column("id", sa.Uuid, nullable=False),
        sa.Column("document_version_id", sa.Uuid, nullable=False),
        sa.Column("section_id", sa.Uuid, nullable=True),
        sa.Column("section_document_version_id", sa.Uuid, nullable=True),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("label", sa.Text, nullable=True),
        sa.Column("caption", sa.Text, nullable=True),
        sa.Column("source_anchor", sa.Text, nullable=True),
        sa.Column("asset_locator", sa.Text, nullable=True),
        sa.Column("content_fingerprint", sa.Text, nullable=True),
        sa.Column("figure_key", sa.Text, nullable=False),
        _ROW_CREATED_AT,
        sa.PrimaryKeyConstraint("id", name="pk_figure"),
        sa.UniqueConstraint(
            "document_version_id", "figure_key", name="uq_figure_document_version_key"
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name="fk_figure_document_version",
        ),
        sa.ForeignKeyConstraint(
            ["section_id", "section_document_version_id"],
            ["section.id", "section.document_version_id"],
            name="fk_figure_section",
        ),
        sa.CheckConstraint(
            "(section_id IS NULL) = (section_document_version_id IS NULL)",
            name="ck_figure_section_pair",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_figure_ordinal_nonnegative"),
        sa.CheckConstraint(
            f"content_fingerprint IS NULL OR content_fingerprint {_HEX64}",
            name="ck_figure_content_fingerprint_hex",
        ),
    )
    op.create_index("ix_figure_document_version_id", "figure", ["document_version_id"])
    op.create_index("ix_figure_section_id", "figure", ["section_id"])

    op.execute(_IMMUTABLE_FUNCTION)
    for _table in _CANONICAL_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{_table}_immutable
            BEFORE UPDATE OR DELETE ON {_table}
            FOR EACH ROW
            EXECUTE FUNCTION dynamisrag_enforce_immutable();
            """
        )


def downgrade() -> None:
    """Revert this revision: drop the canonical schema in dependency order.

    Dropping each table drops its indexes and constraints with it; the
    immutability triggers and their function are dropped explicitly so the
    removal is obvious rather than incidental, leaving revision 0001's empty
    baseline behind.
    """
    for _table in _CANONICAL_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{_table}_immutable ON {_table}")
    op.execute("DROP FUNCTION IF EXISTS dynamisrag_enforce_immutable()")
    op.drop_table("figure")
    op.drop_table("document_table")
    op.drop_table("citation")
    op.drop_table("passage")
    op.drop_table("section")
    op.drop_table("document_version")
    op.drop_table("document_identifier")
    op.drop_table("document")
    op.drop_table("source_artifact")
