"""Typed error surface for the embedding boundary (RES-137).

Deliberately small and deliberately *separate* from the search boundary. An
embedding provider failure is not an ``OpenSearchError``: it happens before any
index exists, and reusing the OpenSearch hierarchy would make a caller that
catches one type silently swallow the other. The same argument rules out reusing
``VectorContractError`` for the embedding contract, even though RES-136's
identity type now lives next to the code that validates it.

    EmbeddingProviderError
      EmbeddingContractError     a local contract violation; nothing was sent
      TeiTransportError           the request never produced a response
      TeiUnexpectedResponse       a response arrived but cannot be trusted
        TeiIdentityError          /info cannot prove an embedding model, or the
                                  server changed under one run
      EmbeddingResponseError      a /embed response failed vector validation
      EmbeddingManifestError      a passage→embedding manifest is unusable

**The untrusted-content policy, stated once**

An embedding input is canonical article text, and a dense vector is derived from
it. Both are therefore treated the way the OpenSearch boundary treats a rejected
projection document: they never enter an exception message, a structured context
field, a log line or a summary.

That rules out every value that is *derived from* the input as well, not just the
input itself. A vector component is refused by name and position only. The
request body is never echoed. And a response body's ``error`` field — TEI's own
prose about what it rejected — is never read: for this endpoint the rejected
thing is a passage, so TEI frequently quotes it back, and relaying that prose
would republish scientific content through a log line or a terminal. Truncation
would not help, because a short quote still leaks.

The single field of a TEI failure envelope that *is* carried is ``error_type``:
a machine-generated classification such as ``Validation``, ``Overloaded``,
``Tokenizer``, ``Backend``, ``Empty`` or ``Unhealthy`` that says what went wrong
without restating the data that caused it. It is bounded and made available as
structured context, exactly as ``error.type`` is at the OpenSearch boundary.

What *is* carried, all of it written by this process or machine-generated by the
server: the operation, the HTTP status, that ``error_type``, the zero-based batch
ordinal, the zero-based input ordinal within the batch, the one-based attempt
number, and a :class:`~dynamisrag.embedding.contracts.EmbeddingInput`
``passage_key`` — a content-addressed key, never the passage it names.

That is why the base class carries *structured fields* alongside ``detail``.
:meth:`EmbeddingProviderError.safe_summary` is assembled from those fields and
never from ``detail``, so a log line, a CLI column or an operator report can be
produced structurally without a further review pass.
"""

from __future__ import annotations

from typing import ClassVar, Final

__all__ = [
    "MAX_SAFE_DETAIL_LENGTH",
    "EmbeddingContractError",
    "EmbeddingManifestError",
    "EmbeddingProviderError",
    "EmbeddingResponseError",
    "TeiIdentityError",
    "TeiTransportError",
    "TeiUnexpectedResponse",
]

MAX_SAFE_DETAIL_LENGTH: Final[int] = 240
"""Longest single fragment an exception message may carry.

A length bound on an *application-authored* line, so a long passage key or a
machine-generated type name cannot push the actionable sentence off the end of a
log line. It is a formatting rule, not a security control: nothing untrusted is
ever shortened into safety by it, because nothing untrusted is ever admitted.
"""


class EmbeddingProviderError(Exception):
    """Base class for every failure at the embedding boundary.

    Two separate views of the same failure:

    ``detail``
        Long-form prose for a human reading a traceback. Written by this
        codebase, so it names the operation, the batch and the position — and
        nothing else. It is a free-form string, and a future caller could point
        it at anything.

    :meth:`safe_summary`
        One line assembled from this exception's class and its structured fields
        only. ``detail`` is deliberately excluded, which is what makes it safe
        to hand to a log, a CLI or an operator report without any further
        review.
    """

    _CATEGORY: ClassVar[str] = "EmbeddingError"
    """Application-authored label for this failure class.

    Set per class so the default summary reads in domain terms
    (``ContractInvalid``, ``ResponseInvalid``) rather than in exception-class
    terms, and overridable per instance where one class covers several distinct
    conditions.
    """

    def __init__(
        self,
        detail: str,
        *,
        operation: str,
        category: str | None = None,
        cause: str | None = None,
        status_code: int | None = None,
        error_type: str | None = None,
        batch_ordinal: int | None = None,
        input_ordinal: int | None = None,
        attempt: int | None = None,
        passage_key: str | None = None,
    ) -> None:
        """Record the prose ``detail`` plus the structured safe context.

        Every optional field is either written by this process (``operation``,
        the ordinals, ``attempt``, ``passage_key``) or machine-generated by the
        server (``status_code``, ``error_type``, ``cause``). None of them can be
        a channel for passage text or a vector component, which is exactly why
        they are the only things a summary is built from.

        ``cause`` is the *class name* of an underlying exception — never its
        message, which a transport library assembles partly from the URL and the
        peer.
        """
        super().__init__(detail)
        self.detail: Final[str] = detail
        self.operation: Final[str] = operation
        self.category: Final[str] = category if category is not None else type(self)._CATEGORY
        self.cause: Final[str | None] = cause
        self.status_code: Final[int | None] = status_code
        self.error_type: Final[str | None] = error_type
        self.batch_ordinal: Final[int | None] = batch_ordinal
        self.input_ordinal: Final[int | None] = input_ordinal
        self.attempt: Final[int | None] = attempt
        self.passage_key: Final[str | None] = passage_key

    def __str__(self) -> str:
        return self.detail

    def safe_summary(self) -> str:
        """A one-line summary built only from controlled values.

        Never derived from ``detail``. The result is safe to log, to print on a
        terminal and to paste into a bug report, and it keeps the facts an
        operator actually needs: the failure category, the operation, the HTTP
        status, the server's ``error_type``, and which batch, input, attempt and
        passage key were involved.
        """
        parts: list[str] = [self.category]
        if self.cause is not None:
            parts.append(f"cause={self.cause}")
        parts.append(f"operation={self.operation}")
        if self.status_code is not None:
            parts.append(f"HTTP {self.status_code}")
        if self.error_type is not None:
            parts.append(f"error_type={self.error_type}")
        if self.batch_ordinal is not None:
            parts.append(f"batch={self.batch_ordinal}")
        if self.input_ordinal is not None:
            parts.append(f"input={self.input_ordinal}")
        if self.attempt is not None:
            parts.append(f"attempt={self.attempt}")
        if self.passage_key is not None:
            parts.append(f"passage_key={self.passage_key}")
        return " ".join(parts)


class EmbeddingContractError(EmbeddingProviderError):
    """A local contract violation was found; no request was sent.

    Raised before any socket is touched for an unusable
    :class:`~dynamisrag.embedding.contracts.EmbeddingInput`, a malformed
    :class:`~dynamisrag.embedding.contracts.EmbeddingGenerationConfig`, a batch
    size below one, or an
    :class:`~dynamisrag.embedding.identity.EmbeddingModelIdentity` that could not
    be reproduced later — a mutable alias, an empty id, a digest that is not a
    digest.

    Every value it reports is configuration, a count, a position or a key this
    process was handed. Passage text and vector components are never among them.
    """

    _CATEGORY: ClassVar[str] = "ContractInvalid"


class TeiTransportError(EmbeddingProviderError):
    """The request never produced a response (connect, TLS, timeout, ...).

    No response means no server text is available and none is wanted, so the
    summary carries only the exception class name and the operation. The
    transport exception's own message is dropped: it is not written by this
    process, and it can quote whatever the URL or the peer put into it.

    ``attempt`` is carried because a transport error is retryable and the
    attempt number is what tells an operator how much of the backoff schedule
    was already spent.
    """

    _CATEGORY: ClassVar[str] = "TransportError"


class TeiUnexpectedResponse(EmbeddingProviderError):
    """A response arrived but its status or payload cannot be trusted.

    Two distinct conditions land here and are told apart by ``category``: a status
    the operation cannot use (``UnexpectedStatus``), and a payload whose shape
    cannot be trusted (``UnexpectedPayload``, the default). Splitting them means an
    operator reading one safe summary line can tell "the server said no" from "the
    server said something I cannot use" without parsing prose.
    """

    _CATEGORY: ClassVar[str] = "UnexpectedPayload"


class TeiIdentityError(TeiUnexpectedResponse):
    """The serving runtime could not be proved to be the expected one.

    Raised, never warned about, for every condition that would make an embedding
    identity unreproducible:

    * ``/info`` does not describe an embedding model;
    * ``/info`` states no immutable ``model_sha``, so the vectors could not be
      regenerated later;
    * the served ``model_id`` is not the configured expectation;
    * the observed ``model_sha`` is not the configured immutable revision;
    * the same identity was not observed before and after one embedding run, so
      some vectors were generated by one runtime and others by another.

    Failing closed is the whole point. A TEI deployment that was restarted on a
    floating tag between two batches produces a set of vectors that no single
    model identity describes; indexing them together would produce an index that
    cannot be rebuilt and cannot be compared with anything.
    """

    _CATEGORY: ClassVar[str] = "IdentityUnproven"


class EmbeddingResponseError(EmbeddingProviderError):
    """A ``/embed`` response could not be validated into dense vectors.

    Every condition here is a shape or arithmetic property, identified by batch
    ordinal, input ordinal and component position: a response that is not an
    ordered list, a cardinality that does not match the request, an empty vector,
    a component that is not a finite number, or a dimension that disagrees with
    another vector in the same run or with the requested dimensions.

    Returned components are never normalized, clipped, rounded, padded,
    truncated or repaired. A vector that is not exactly what the model returned
    is not that model's output, so it is refused rather than corrected, and no
    component value is ever named in the message.
    """

    _CATEGORY: ClassVar[str] = "ResponseInvalid"


class EmbeddingManifestError(EmbeddingProviderError):
    """A passage→embedding manifest cannot be built or cannot be trusted.

    Raised for a duplicate ``passage_key``, an empty entry set, a dimension that
    the entries contradict, or a caller-supplied value set that does not match the
    inputs it claims to embed. The manifest is the RES-137 artifact, so a
    manifest that cannot state exactly which vectors belong to which passage is
    refused before it can become a downstream index identity.
    """

    _CATEGORY: ClassVar[str] = "ManifestInvalid"
