"""PostgreSQL access layer (SQLAlchemy 2.x over psycopg 3)."""

from __future__ import annotations

from dynamisrag.db.canonical import (
    get_citation_resolutions,
    get_document,
    get_document_identifiers,
    get_document_version,
    get_section,
    get_source_artifact,
    get_source_artifact_by_key,
    insert_citation,
    insert_citation_resolution,
    insert_document,
    insert_document_identifier,
    insert_document_table,
    insert_document_version,
    insert_figure,
    insert_passage,
    insert_section,
    insert_source_artifact,
    list_citations,
    list_document_tables,
    list_document_versions,
    list_figures,
    list_passages,
    list_sections,
)
from dynamisrag.db.engine import create_database_engine
from dynamisrag.db.errors import SemanticParentKeyError
from dynamisrag.db.models import (
    Base,
    CitationRecord,
    CitationResolutionRecord,
    DocumentIdentifierRecord,
    DocumentRecord,
    DocumentTableRecord,
    DocumentVersionRecord,
    FigureRecord,
    ParagraphRecord,
    PassageRecord,
    SectionRecord,
    SourceArtifactRecord,
)
from dynamisrag.db.probe import POSTGRES_DEPENDENCY_NAME, check_postgres

__all__ = [
    "POSTGRES_DEPENDENCY_NAME",
    "Base",
    "CitationRecord",
    "CitationResolutionRecord",
    "DocumentIdentifierRecord",
    "DocumentRecord",
    "DocumentTableRecord",
    "DocumentVersionRecord",
    "FigureRecord",
    "ParagraphRecord",
    "PassageRecord",
    "SectionRecord",
    "SemanticParentKeyError",
    "SourceArtifactRecord",
    "check_postgres",
    "create_database_engine",
    "get_citation_resolutions",
    "get_document",
    "get_document_identifiers",
    "get_document_version",
    "get_section",
    "get_source_artifact",
    "get_source_artifact_by_key",
    "insert_citation",
    "insert_citation_resolution",
    "insert_document",
    "insert_document_identifier",
    "insert_document_table",
    "insert_document_version",
    "insert_figure",
    "insert_passage",
    "insert_section",
    "insert_source_artifact",
    "list_citations",
    "list_document_tables",
    "list_document_versions",
    "list_figures",
    "list_passages",
    "list_sections",
]
