"""Deterministic identity primitives for the canonical document model.

Project principle: *everything deterministically computable must be
deterministic.* Every function in this module is pure — same inputs, same
output, no randomness, no clock, no I/O — so a canonical key or fingerprint
can be recomputed anywhere (application code, database migration, tests) and
always agrees.

Identity is never derived from database surrogate keys and never generated by
the model layer. A canonical key is a SHA-256 digest over the semantic
inputs that define an entity's logical identity, so two independently
computed views of the same logical record collide on purpose and any change
to a relevant input changes the derived identity.
"""

from __future__ import annotations

import hashlib
from collections.abc import Iterable
from uuid import UUID

__all__ = [
    "UNIT_SEPARATOR",
    "citation_key",
    "digest",
    "document_canonical_key",
    "document_table_key",
    "document_version_key",
    "figure_key",
    "passage_key",
    "section_key",
    "source_artifact_key",
]

UNIT_SEPARATOR = "\x1f"
"""Unit separator between digested parts.

ASCII 0x1F is the standard "field boundary" control character: it can never
appear in well-formed text input, so concatenating parts with it is
unambiguous regardless of what the parts contain.
"""


def digest(*parts: str) -> str:
    """Return the lowercase SHA-256 hex digest of the unit-separated parts."""
    return hashlib.sha256(UNIT_SEPARATOR.join(parts).encode("utf-8")).hexdigest()


def _optional(*parts: str | None) -> Iterable[str]:
    """Render optional identity inputs as empty strings so keys stay total."""
    return (part or "" for part in parts)


def normalize_doi(value: str | None) -> str | None:
    """Canonicalize a DOI to its bare lowercase registrant/suffix form.

    ``10.1038/nature12373``, ``doi:10.1038/nature12373`` and
    ``https://doi.org/10.1038/nature12373`` denote the same work and must
    produce the same identity, so the common resolver prefixes are stripped
    and the remainder is lowercased (DOIs are case-insensitive by spec).
    """
    if value is None:
        return None
    normalized = value.strip().lower()
    for prefix in ("doi:", "https://doi.org/", "http://dx.doi.org/"):
        if normalized.startswith(prefix):
            normalized = normalized[len(prefix) :]
            break
    return normalized or None


def source_artifact_key(source_system: str, source_external_id: str, content_sha256: str) -> str:
    """Identity of one exact acquired artifact: where it came from, which
    external object it is, and the exact bytes that were acquired.

    The content digest is part of the identity on purpose: the same external
    object re-acquired with different bytes is a different artifact and must
    not silently alias an existing one.
    """
    return digest(source_system, source_external_id, content_sha256)


def document_canonical_key(
    *,
    doi: str | None,
    pmid: str | None,
    pmcid: str | None,
    title: str | None,
) -> str:
    """Stable identity of a logical scientific work across every acquired and
    normalized version of it.

    Strongest available identifier wins: DOI, then PMID, then PMCID, then a
    digest of the normalized title. A work with none of these has no
    deterministic identity and is rejected rather than guessed at.
    """
    normalized_doi = normalize_doi(doi)
    if normalized_doi:
        return f"doi:{normalized_doi}"
    normalized_pmid = pmid.strip() if pmid else None
    if normalized_pmid:
        return f"pmid:{normalized_pmid}"
    normalized_pmcid = pmcid.strip() if pmcid else None
    if normalized_pmcid:
        return f"pmcid:{normalized_pmcid}"
    normalized_title = title.strip() if title else None
    if normalized_title:
        return f"title:{digest(normalized_title)}"
    raise ValueError(
        "document identity requires at least one of: doi, pmid, pmcid, title"
    )


def document_version_key(
    document_id: UUID,
    source_artifact_id: UUID,
    parser_revision: str,
    normalizer_revision: str,
    content_fingerprint: str,
) -> str:
    """Identity of one immutable canonical version of a document.

    Binds the logical document, the exact source artifact it was derived
    from, the processing configuration (parser and normalizer revisions) and
    the canonical content fingerprint. Re-persisting the same deterministic
    version identity is therefore a no-op collision, not an ambiguous second
    version.
    """
    return digest(
        str(document_id),
        str(source_artifact_id),
        parser_revision,
        normalizer_revision,
        content_fingerprint,
    )


def section_key(document_version_id: UUID, structural_path: str) -> str:
    """Identity of a structural node: its document version plus its
    dot-joined ordinal path from the root (``1``, ``1.2``, ``1.2.3``...)."""
    return digest(str(document_version_id), structural_path)


def passage_key(document_version_id: UUID, chunker_revision: str, ordinal: int) -> str:
    """Identity of a retrieval unit: document version, chunker revision and
    the passage's deterministic ordinal within that chunker's output.

    Ordinals are unique across the whole document version for one chunker
    revision, so the triple never collides across sections. A different
    chunker revision produces an independent, coexisting passage set.
    """
    return digest(str(document_version_id), chunker_revision, str(ordinal))


def citation_key(
    document_version_id: UUID,
    ordinal: int,
    source_reference_id: str | None,
    raw_reference_text: str | None,
) -> str:
    """Identity of a bibliographic reference: its document version, its
    ordinal in the reference list, and the source anchor / raw text that pin
    it to the document."""
    return digest(str(document_version_id), str(ordinal), *_optional(source_reference_id, raw_reference_text))


def document_table_key(
    document_version_id: UUID,
    ordinal: int,
    label: str | None,
    caption: str | None,
    source_anchor: str | None,
) -> str:
    """Identity of a scientific table within a document version."""
    return digest(str(document_version_id), str(ordinal), *_optional(label, caption, source_anchor))


def figure_key(
    document_version_id: UUID,
    ordinal: int,
    label: str | None,
    caption: str | None,
    source_anchor: str | None,
) -> str:
    """Identity of a scientific figure within a document version."""
    return digest(str(document_version_id), str(ordinal), *_optional(label, caption, source_anchor))
