"""Deterministic identity primitives for the canonical document model.

Project principle: *everything deterministically computable must be
deterministic.* Every function in this module is pure — same inputs, same
output, no randomness, no clock, no I/O — so a canonical key or fingerprint
can be recomputed anywhere (application code, database migration, tests) and
always agrees.

Identity is never derived from database surrogate keys and never generated by
the model layer. A canonical key is a SHA-256 digest over the semantic
inputs that define an entity's logical identity, so two independently
computed views of the same logical record collide on purpose and any change
to a relevant input changes the derived identity.

Every entity key is derived from its *semantic parent keys*, never from the
surrogate ``uuid4`` primary keys the database assigns: a section key digests
its document version's ``version_key``, a passage key digests the same
``version_key``, and so on up the hierarchy. The same semantic corpus
processed with the same algorithms therefore produces the same canonical
identities regardless of database instance, insertion order or random
surrogate ids.
"""

from __future__ import annotations

import hashlib
from collections.abc import Iterable

__all__ = [
    "UNIT_SEPARATOR",
    "citation_key",
    "digest",
    "document_canonical_key",
    "document_table_key",
    "document_version_key",
    "figure_key",
    "passage_key",
    "section_key",
    "source_artifact_key",
]

UNIT_SEPARATOR = "\x1f"
"""Unit separator between digested parts.

ASCII 0x1F is the standard "field boundary" control character: it can never
appear in well-formed text input, so concatenating parts with it is
unambiguous regardless of what the parts contain.
"""


def digest(*parts: str) -> str:
    """Return the lowercase SHA-256 hex digest of the unit-separated parts."""
    return hashlib.sha256(UNIT_SEPARATOR.join(parts).encode("utf-8")).hexdigest()


def _optional(*parts: str | None) -> Iterable[str]:
    """Render optional identity inputs as empty strings so keys stay total."""
    return (part or "" for part in parts)


def normalize_doi(value: str | None) -> str | None:
    """Canonicalize a DOI to its bare lowercase registrant/suffix form.

    ``10.1038/nature12373``, ``doi:10.1038/nature12373`` and
    ``https://doi.org/10.1038/nature12373`` denote the same work and must
    produce the same identity, so the common resolver prefixes are stripped
    and the remainder is lowercased (DOIs are case-insensitive by spec).
    """
    if value is None:
        return None
    normalized = value.strip().lower()
    for prefix in ("doi:", "https://doi.org/", "http://dx.doi.org/"):
        if normalized.startswith(prefix):
            normalized = normalized[len(prefix) :]
            break
    return normalized or None


def source_artifact_key(source_system: str, source_external_id: str, content_sha256: str) -> str:
    """Identity of one exact acquired artifact: where it came from, which
    external object it is, and the exact bytes that were acquired.

    The content digest is part of the identity on purpose: the same external
    object re-acquired with different bytes is a different artifact and must
    not silently alias an existing one.
    """
    return digest(source_system, source_external_id, content_sha256)


def document_canonical_key(
    *,
    doi: str | None,
    pmid: str | None,
    pmcid: str | None,
    title: str | None,
) -> str:
    """Creation-time identity basis of a logical scientific work.

    Strongest identifier known when the document is first ingested wins: DOI,
    then PMID, then PMCID, then a digest of the normalized title. The derived
    key is fixed at creation and never recomputed: identifiers discovered
    later are attached as ``document_identifier`` aliases and never change the
    document's canonical identity. A work with none of these inputs has no
    deterministic identity and is rejected rather than guessed at.
    """
    normalized_doi = normalize_doi(doi)
    if normalized_doi:
        return f"doi:{normalized_doi}"
    normalized_pmid = pmid.strip() if pmid else None
    if normalized_pmid:
        return f"pmid:{normalized_pmid}"
    normalized_pmcid = pmcid.strip() if pmcid else None
    if normalized_pmcid:
        return f"pmcid:{normalized_pmcid}"
    normalized_title = title.strip() if title else None
    if normalized_title:
        return f"title:{digest(normalized_title)}"
    raise ValueError("document identity requires at least one of: doi, pmid, pmcid, title")


def document_version_key(
    document_canonical_key: str,
    source_artifact_key: str,
    parser_revision: str,
    normalizer_revision: str,
    content_fingerprint: str,
) -> str:
    """Identity of one immutable canonical version of a document.

    Derived from the semantic parent identities — the document's canonical key
    and the source artifact's artifact key — plus the processing configuration
    (parser and normalizer revisions) and the canonical content fingerprint.
    Never from surrogate database ids: the same logical document derived from
    the same artifact under the same configuration is the same version in
    every database, so re-persisting it collides on the unique
    ``version_key`` instead of creating an ambiguous second version.
    """
    return digest(
        document_canonical_key,
        source_artifact_key,
        parser_revision,
        normalizer_revision,
        content_fingerprint,
    )


def section_key(version_key: str, structural_path: str) -> str:
    """Identity of a structural node: its document version's canonical key
    plus its dot-joined ordinal path from the root (``1``, ``1.2``,
    ``1.2.3``...)."""
    return digest(version_key, structural_path)


def passage_key(version_key: str, chunker_revision: str, ordinal: int) -> str:
    """Identity of a retrieval unit: the document version's canonical key, the
    chunker revision and the passage's deterministic ordinal within that
    chunker's output.

    Ordinals are unique across the whole document version for one chunker
    revision, so the triple never collides across sections. A different
    chunker revision produces an independent, coexisting passage set.
    """
    return digest(version_key, chunker_revision, str(ordinal))


def citation_key(
    version_key: str,
    ordinal: int,
    source_reference_id: str | None,
    raw_reference_text: str | None,
) -> str:
    """Identity of a bibliographic reference: its document version's canonical
    key, its ordinal in the reference list, and the source anchor / raw text
    that pin it to the document."""
    return digest(version_key, str(ordinal), *_optional(source_reference_id, raw_reference_text))


def document_table_key(
    version_key: str,
    ordinal: int,
    label: str | None,
    caption: str | None,
    source_anchor: str | None,
) -> str:
    """Identity of a scientific table within a document version, derived from
    the version's canonical key plus the table's structural identity."""
    return digest(version_key, str(ordinal), *_optional(label, caption, source_anchor))


def figure_key(
    version_key: str,
    ordinal: int,
    label: str | None,
    caption: str | None,
    source_anchor: str | None,
) -> str:
    """Identity of a scientific figure within a document version, derived from
    the version's canonical key plus the figure's structural identity."""
    return digest(version_key, str(ordinal), *_optional(label, caption, source_anchor))
